apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-client
spec:
  replicas: 3
  template:
    spec:
      containers:
        name: go-client
        image: radumatei/codecamp-client:1
        ports:
        - containerPort: 80